### ISSUE TITLE
CI experiment

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#14]
I want to try an experiment,
of building openplc agains different libs version..

Can u give me a hint as to which are "externals"
eg

dnp3 is here https://github.com/automatak/dnp3 and all the "tags"

which are the other externals.. ?

libmodbus = https://github.com/stephane/libmodbus
matiec = https://bitbucket.org/mjsousa/matiec (NO TAGS)
?

**Comment by thiagoralves** [comment]
Yes, those are the correct locations. There are all libs you will need.

**Comment by shrmrf** [comment]
@pedromorgan @thiagoralves did you guys get the CI/CD thing running? 

I can help set up the builds if you want. Maybe we should also publish official docker images on Docker Hub?

**Comment by pedromorgan** [comment]
@shrmrf I got a "basic" working on gitlab, but would be cool to have docker (altought never used as yet)

https://gitlab.com/openplcproject/openplc_v3/blob/master/.gitlab-ci.yml

**Comment by pedromorgan** [comment]
@shrmrf @thiagoralves  gitlab allows for different builds jobs with images libs etc (example below)

This also means we can test against differrent version of eg dnp3, modbus etc


eg
```
before_script:
   - apt-get install --yes cmake libmatio-dev libblas-dev libsqlite3-dev libcurl4-openssl-dev
   - apt-get install --yes libarchive-dev liblzma-dev

build:precise:
  image: precise:base
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug ../
    - make

build:trusty:
  image: trusty:base
  script:
    - mkdir build/
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Debug ../
    - make
```
